version: "3.8"
services:
  backend:
    image: "backend"
    build: ./BackEnd
    ports:
      - "80:80"
    volumes:
      - ./BackEnd:/app
      - /app/node_modules
    env_file:
      - ./ENV/config.env

  frontend:
    image: "frontend"
    build: ./frontEnd
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

  commdevice:
    image: "commdevice"
    build: ./commDevice
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - frontend
    volumes:
      - ./commDevice/remoteIO:/app/commdevice
#networks:
#  tim_net:
#    external: true
# volumes:
#   data:
